### ISSUE TITLE
Getting Empty Measures

### ISSUE THREAD

**Issue by thomashs** [rsim/mondrian_demo#6]
I have successfully created a connection with JDBC postgres adapter on top of Rails 4.2.3 - When I run queries I get empty measures.. but the dimensions are retrieved correctly.

**Comment by rsim** [comment]
Please describe in more details this problem if you need help - currently unfortunately I don't have a clue what is wrong.

**Comment by thomashs** [comment]
Raimonds! Sorry for such a poor description of my problem. It turns out that I managed to solve my problem by creating the dimensions one by one and discovering that it was a multidimensional faulty schema caused by a couple of faulty dimensions.. Thanks for answering me anyway :+1:
